---                                                             
version: '3.4'
services:
  pdns:
    image: powerdns/pdns-auth-46
    environment:
      - PDNS_AUTH_API_KEY
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8281:8081"
    volumes:
      - type: bind
        source: ./pdns-custom.conf
        target: /etc/powerdns/pdns.d/pdns-custom.conf
      - type: volume
        source: pdnsdb
        target: /var/lib/powerdns
  admin:
    build: 
      context: PowerDNS-Admin-DomainConnect
      dockerfile: docker/Dockerfile
    image: powerdns-admin
    container_name: powerdns_admin
    restart: unless-stopped
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - pdnsadmindb:/data
      - ./PowerDNS-Admin-DomainConnect/powerdnsadmin/routes:/app/powerdnsadmin/routes
      - ./PowerDNS-Admin-DomainConnect/powerdnsadmin/lib:/app/powerdnsadmin/lib
      - ./PowerDNS-Admin-DomainConnect/powerdnsadmin/templates:/app/powerdnsadmin/templates
      - ./PowerDNS-Admin-DomainConnect/powerdnsadmin/models:/app/powerdnsadmin/models
      - ./PowerDNS-Admin-DomainConnect/powerdnsadmin/decorators.py:/app/powerdnsadmin/decorators.py
      - ./Templates:/app/DomainConnectTemplates
    environment:
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - OFFLINE_MODE=False
    command:
      - "gunicorn"
      - "powerdnsadmin:create_app()"
      - "--reload"
volumes:
  pdnsdb:
  pdnsadmindb:
