---                                                             
version: '3.4'
services:
  pdns:
    image: powerdns/pdns-auth-46
    environment:
      - PDNS_AUTH_API_KEY
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8281:8081"
    volumes:
      - type: bind
        source: ./pdns-custom.conf
        target: /etc/powerdns/pdns.d/pdns-custom.conf
      - type: volume
        source: pdnsdb
        target: /var/lib/powerdns
  admin:
    image: ngoduykhanh/powerdns-admin:latest
    container_name: powerdns_admin
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - pdnsadmindb:/data
    environment:
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - OFFLINE_MODE=False
volumes:
  pdnsdb:
  pdnsadmindb:
