---                                                             
version: '2'
services:
  pdns:
    image: powerdns/pdns-auth-46
    environment:
      - PDNS_AUTH_API_KEY=CHANGEME #change the key to sth secret
    ports:
      - "53:8053"
      - "53:8053/udp"
#      - "8281:8081" // uncomment to expose powerdns API. 8081 is the internal port for admin
    volumes:
      - ./pdns-custom.conf:/etc/powerdns/pdns.d/pdns-custom.conf
      - pdnsdb:/var/lib/powerdns
    cap_add:
      - NET_BIND_SERVICE
  admin:
    build: 
      context: PowerDNS-Admin-DomainConnect
      dockerfile: docker/Dockerfile
    image: powerdns-admin
    container_name: powerdns_admin
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - pdnsadmindb:/data
    environment:
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - OFFLINE_MODE=False
volumes:
  pdnsdb:
  pdnsadmindb:
